### ISSUE TITLE
question for bias setting.

### ISSUE THREAD

**Issue by myoh97** [wkim97/FSR#3]
Thanks for your great work.

I found all the biases are set to False in your Separation and Recalibration network.
Is there any reason you did?

**Comment by wkim97** [comment]
There is no specific reason why we set bias=False in Sep and Rec networks.
One reason was to keep consistency with ResNet-18, which served as our main backbone network and uses conv2d layers with bias=False.

While we haven't tested it, my guess would be setting bias=True wouldn't hugely affect what Sep and Rec networks learn.

**Comment by myoh97** [comment]
Thanks for your quick response. i got it.
