### ISSUE TITLE
Doubts about model output！

### ISSUE THREAD

**Issue by BigBeardYT** [wkim97/FSR#4]
If I take the four outputs out, r_outputs, nr_outputs, rec_outputs from the back of your model and give them in order to just use out, and then do the adversarial training separately afterward, will the results have a big impact?

**Comment by wkim97** [comment]
Hi,

I'm not sure if I understood your question correctly.
Adversarial training involves training the model with adversarial examples, so training only w/ out will still be considered adversarial training.
What do you mean by doing adversarial training separately afterward?
